import express from 'express';
import type { Router } from 'express';
import { errorHandler } from '../middleware/error-handler.js';

/**
 * Creates a minimal Express app for testing with JSON parsing and error handler.
 */
export function createTestApp(router: Router, basePath = '/') {
  const app = express();
  app.use(express.json());
  app.use(basePath, router);
  app.use(errorHandler);
  return app;
}

/**
 * Lightweight request helper using Node fetch.
 */
export function request(
  app: express.Express,
  method: string,
  path: string,
  body?: unknown,
  headers?: Record<string, string>,
) {
  return new Promise<{ status: number; body: Record<string, unknown> }>((resolve) => {
    const server = app.listen(0, () => {
      const addr = server.address() as { port: number };
      const bodyStr = body ? JSON.stringify(body) : undefined;
      const opts: RequestInit = {
        method,
        headers: {
          'Content-Type': 'application/json',
          ...headers,
        },
        ...(bodyStr ? { body: bodyStr } : {}),
      };

      fetch(`http://127.0.0.1:${addr.port}${path}`, opts)
        .then((res) =>
          res
            .json()
            .then((json) => ({ status: res.status, body: json as Record<string, unknown> })),
        )
        .then((result) => {
          server.close();
          resolve(result);
        });
    });
  });
}

/**
 * Returns Authorization header with a mock Bearer token.
 */
export function authHeaders(token = 'mock-jwt-token') {
  return { Authorization: `Bearer ${token}` };
}

interface MockUserData {
  id: string;
  email: string;
  name: string | null;
  passwordHash: string;
  onboardedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

interface MockProjectData {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  keywords: string[];
  niche: string | null;
  category: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

interface MockSourceData {
  id: string;
  projectId: string;
  platform: 'REDDIT' | 'HACKERNEWS' | 'TWITTER' | 'PRODUCTHUNT';
  url: string;
  config: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
}

interface MockInsightData {
  id: string;
  projectId: string;
  type: 'PAIN_POINT' | 'FEATURE_REQUEST' | 'COMPETITOR' | 'TREND' | 'SENTIMENT';
  title: string;
  description: string;
  severity: number;
  confidence: number;
  tags: string[];
  metadata: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
}

interface MockSpecData {
  id: string;
  projectId: string;
  title: string;
  content: string;
  format: 'MARKDOWN' | 'CLAUDE_CODE' | 'LINEAR';
  version: number;
  createdAt: Date;
  updatedAt: Date;
}

interface MockScrapeJobData {
  id: string;
  sourceId: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  startedAt: Date | null;
  completedAt: Date | null;
  error: string | null;
  postsFound: number;
  createdAt: Date;
}

export function mockUser(overrides?: Partial<MockUserData>): MockUserData {
  return {
    id: 'user-1',
    email: 'test@example.com',
    name: 'Test User',
    passwordHash: 'hashed-password',
    onboardedAt: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    ...overrides,
  };
}

export function mockProject(overrides?: Partial<MockProjectData>): MockProjectData {
  return {
    id: 'project-1',
    userId: 'user-1',
    name: 'Test Project',
    description: 'A test project',
    keywords: ['test'],
    niche: null,
    category: null,
    isAutoGenerated: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    ...overrides,
  };
}

export function mockSource(overrides?: Partial<MockSourceData>): MockSourceData {
  return {
    id: 'source-1',
    projectId: 'project-1',
    platform: 'REDDIT',
    url: 'https://reddit.com/r/test',
    config: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    ...overrides,
  };
}

export function mockInsight(overrides?: Partial<MockInsightData>): MockInsightData {
  return {
    id: 'insight-1',
    projectId: 'project-1',
    type: 'PAIN_POINT',
    title: 'Test Insight',
    description: 'A test insight description',
    severity: 0.7,
    confidence: 0.8,
    tags: ['test'],
    metadata: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    ...overrides,
  };
}

export function mockSpec(overrides?: Partial<MockSpecData>): MockSpecData {
  return {
    id: 'spec-1',
    projectId: 'project-1',
    title: 'Test Spec',
    content: '# Test Spec Content',
    format: 'MARKDOWN',
    version: 1,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    ...overrides,
  };
}

export function mockScrapeJob(overrides?: Partial<MockScrapeJobData>): MockScrapeJobData {
  return {
    id: 'job-1',
    sourceId: 'source-1',
    status: 'COMPLETED',
    startedAt: new Date('2024-01-01'),
    completedAt: new Date('2024-01-01'),
    error: null,
    postsFound: 10,
    createdAt: new Date('2024-01-01'),
    ...overrides,
  };
}
