export interface Project {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  keywords: string[];
  niche: string | null;
  category: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}
