import { prisma } from '../lib/prisma.js';
import { CATEGORY_SOURCES } from '../data/category-sources.js';
import { enqueueScrapeJob } from './queue/jobs.js';
import { logger } from '../utils/logger.js';

const VALID_CATEGORIES = [
  'SAAS', 'DEVTOOLS', 'AI_ML', 'FINTECH', 'ECOMMERCE',
  'MOBILE', 'GAMING', 'HEALTH', 'EDUCATION', 'SOCIAL', 'SECURITY',
] as const;

type Category = (typeof VALID_CATEGORIES)[number];

function isValidCategory(value: string): value is Category {
  return (VALID_CATEGORIES as readonly string[]).includes(value);
}

export async function completeOnboarding(userId: string, categories: string[]): Promise<void> {
  const validCategories = categories.filter(isValidCategory);
  if (validCategories.length === 0) {
    throw new Error('At least one valid category is required');
  }

  // Create UserInterest records
  await prisma.userInterest.createMany({
    data: validCategories.map((category) => ({ userId, category })),
    skipDuplicates: true,
  });

  // For each category, create project + sources + enqueue scrape jobs
  for (const category of validCategories) {
    const project = await prisma.project.create({
      data: {
        userId,
        name: `${category} Discovery`,
        description: `Auto-generated discovery project for ${category}`,
        isAutoGenerated: true,
        category,
        keywords: [category],
      },
    });

    const sources = CATEGORY_SOURCES[category];
    if (!sources) continue;

    for (const sourceData of sources) {
      const source = await prisma.source.create({
        data: {
          projectId: project.id,
          platform: sourceData.platform,
          url: sourceData.url,
        },
      });

      const scrapeJob = await prisma.scrapeJob.create({
        data: { sourceId: source.id, status: 'PENDING' },
      });

      await enqueueScrapeJob(source.id);
      logger.info({ sourceId: source.id, scrapeJobId: scrapeJob.id, category }, 'Enqueued initial scrape job');
    }
  }

  // Mark user as onboarded
  await prisma.user.update({
    where: { id: userId },
    data: { onboardedAt: new Date() },
  });

  logger.info({ userId, categories: validCategories }, 'Onboarding completed');
}
