import { Router } from 'express';
import { prisma } from '../lib/prisma.js';
import { redis } from '../lib/redis.js';
import { sendSuccess } from '../lib/response.js';
import { discoverQuerySchema } from '@promptops/shared';

export const discoverRouter = Router();

const DISCOVER_CACHE_TTL = 60; // seconds

discoverRouter.get('/', async (req, res) => {
  const userId = req.userId!;
  const { category, type, minSeverity, tag, cursor, limit } = discoverQuerySchema.parse(req.query);

  // Redis cache for discover — 60s TTL
  const cacheKey = `discover:${userId}:${category ?? ''}:${type ?? ''}:${minSeverity ?? ''}:${tag ?? ''}:${cursor ?? ''}:${limit}`;
  const cached = await redis.get(cacheKey);
  if (cached) {
    const { data, meta } = JSON.parse(cached) as {
      data: unknown[];
      meta: { cursor: string | null; hasMore: boolean };
    };
    sendSuccess(res, data, meta);
    return;
  }

  // Get user's interest categories
  const interests = await prisma.userInterest.findMany({
    where: { userId },
    select: { category: true },
  });
  const userCategories = interests.map((i) => i.category);

  if (userCategories.length === 0) {
    sendSuccess(res, [], { cursor: null, hasMore: false });
    return;
  }

  // Build filter for insights from user's auto-generated projects
  const where: Record<string, unknown> = {
    project: {
      userId,
      isAutoGenerated: true,
      ...(category ? { category: category } : { category: { in: userCategories } }),
    },
  };

  if (type) where['type'] = type;
  if (minSeverity) where['severity'] = { gte: minSeverity };
  if (tag) where['tags'] = { has: tag };
  if (cursor) where['id'] = { lt: cursor };

  const insights = await prisma.insight.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: limit + 1,
    include: {
      project: { select: { name: true, category: true } },
      savedBy: { where: { userId }, select: { id: true } },
    },
  });

  const hasMore = insights.length > limit;
  const items = hasMore ? insights.slice(0, limit) : insights;

  const result = items.map((insight) => ({
    id: insight.id,
    projectId: insight.projectId,
    type: insight.type,
    title: insight.title,
    description: insight.description,
    severity: insight.severity,
    confidence: insight.confidence,
    tags: insight.tags,
    metadata: insight.metadata,
    createdAt: insight.createdAt,
    updatedAt: insight.updatedAt,
    category: insight.project.category,
    isSaved: insight.savedBy.length > 0,
    projectName: insight.project.name,
  }));

  const meta = {
    cursor: items.length > 0 ? items[items.length - 1]!.id : null,
    hasMore,
  };

  // Cache result for 60 seconds
  await redis.setex(cacheKey, DISCOVER_CACHE_TTL, JSON.stringify({ data: result, meta }));

  sendSuccess(res, result, meta);
});
