import { Router } from 'express';
import { prisma } from '../lib/prisma.js';
import { redis } from '../lib/redis.js';
import { sendSuccess } from '../lib/response.js';
import { askClaude } from '../utils/claude.js';
import { logger } from '../utils/logger.js';
import { discoverQuerySchema } from '@promptops/shared';

export const discoverRouter = Router();

const DISCOVER_CACHE_TTL = 60; // seconds
const TAGS_CACHE_TTL = 300; // 5 minutes

type InsightRow = {
  id: string;
  projectId: string;
  type: string;
  title: string;
  description: string;
  severity: number;
  confidence: number;
  tags: string[];
  metadata: unknown;
  createdAt: Date;
  updatedAt: Date;
  project: { name: string; category: string | null };
  savedBy: { id: string }[];
};

function toResult(insight: InsightRow) {
  return {
    id: insight.id,
    projectId: insight.projectId,
    type: insight.type,
    title: insight.title,
    description: insight.description,
    severity: insight.severity,
    confidence: insight.confidence,
    tags: insight.tags,
    metadata: insight.metadata,
    createdAt: insight.createdAt,
    updatedAt: insight.updatedAt,
    category: insight.project.category,
    isSaved: insight.savedBy.length > 0,
    projectName: insight.project.name,
  };
}

// GET /discover/tags — most frequent tags for user's interest categories
discoverRouter.get('/tags', async (req, res) => {
  const userId = req.userId!;

  const cacheKey = `discover-tags:${userId}`;
  const cached = await redis.get(cacheKey);
  if (cached) {
    sendSuccess(res, JSON.parse(cached) as string[]);
    return;
  }

  const interests = await prisma.userInterest.findMany({
    where: { userId },
    select: { category: true },
  });
  const userCategories = interests.map((row) => row.category);

  if (userCategories.length === 0) {
    sendSuccess(res, []);
    return;
  }

  const rawInsights = await prisma.insight.findMany({
    where: {
      project: { userId, isAutoGenerated: true, category: { in: userCategories } },
    },
    select: { tags: true },
    take: 500,
  });

  const tagCounts = new Map<string, number>();
  for (const insight of rawInsights) {
    for (const tag of insight.tags) {
      tagCounts.set(tag, (tagCounts.get(tag) ?? 0) + 1);
    }
  }

  const sortedTags = [...tagCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 30)
    .map(([tag]) => tag);

  await redis.setex(cacheKey, TAGS_CACHE_TTL, JSON.stringify(sortedTags));
  sendSuccess(res, sortedTags);
});

// GET /discover/semantic?q= — AI-powered semantic search
discoverRouter.get('/semantic', async (req, res) => {
  const userId = req.userId!;
  const q = typeof req.query['q'] === 'string' ? req.query['q'].trim() : '';
  if (!q) {
    sendSuccess(res, []);
    return;
  }

  const cacheKey = `discover-semantic:${userId}:${q.toLowerCase().slice(0, 80)}`;
  const cached = await redis.get(cacheKey);
  if (cached) {
    sendSuccess(res, JSON.parse(cached) as unknown[]);
    return;
  }

  let keywords: string[] = [];
  try {
    const raw = await askClaude(
      'You are a search query expansion assistant. Return ONLY a JSON array of 5-8 lowercase keywords that best capture the intent of the user query. No markdown, no explanation.',
      `User query: "${q}"`,
      { model: 'claude-haiku-4-5-20251001', maxTokens: 256, temperature: 0.2 },
    );
    const cleaned = raw
      .replace(/```(?:json)?\n?/g, '')
      .replace(/```\s*$/g, '')
      .trim();
    const parsed = JSON.parse(cleaned) as unknown;
    if (Array.isArray(parsed)) {
      keywords = parsed.filter((k): k is string => typeof k === 'string').slice(0, 8);
    }
  } catch (err) {
    logger.warn({ err }, 'Semantic search: keyword expansion failed, falling back to raw query');
    keywords = q.toLowerCase().split(/\s+/).slice(0, 5);
  }

  const interests = await prisma.userInterest.findMany({
    where: { userId },
    select: { category: true },
  });
  const userCategories = interests.map((row) => row.category);

  const keywordConditions = keywords.map((kw) => ({
    OR: [
      { title: { contains: kw, mode: 'insensitive' as const } },
      { description: { contains: kw, mode: 'insensitive' as const } },
      { tags: { has: kw } },
    ],
  }));

  const insights = (await prisma.insight.findMany({
    where: {
      project: { userId, isAutoGenerated: true, category: { in: userCategories } },
      OR: keywordConditions,
    },
    orderBy: { severity: 'desc' },
    take: 30,
    include: {
      project: { select: { name: true, category: true } },
      savedBy: { where: { userId }, select: { id: true } },
    },
  })) as InsightRow[];

  const result = insights.map(toResult);

  await redis.setex(cacheKey, DISCOVER_CACHE_TTL, JSON.stringify(result));
  sendSuccess(res, result);
});

// GET /discover — main feed with all filters
discoverRouter.get('/', async (req, res) => {
  const userId = req.userId!;
  const { category, type, minSeverity, tag, search, sort, dateRange, cursor, limit } =
    discoverQuerySchema.parse(req.query);

  const cacheKey = `discover:${userId}:${category ?? ''}:${type ?? ''}:${minSeverity ?? ''}:${tag ?? ''}:${search ?? ''}:${sort}:${dateRange}:${cursor ?? ''}:${limit}`;

  if (sort !== 'relevance') {
    const cached = await redis.get(cacheKey);
    if (cached) {
      const { data, meta } = JSON.parse(cached) as {
        data: unknown[];
        meta: { cursor: string | null; hasMore: boolean };
      };
      sendSuccess(res, data, meta);
      return;
    }
  }

  const interests = await prisma.userInterest.findMany({
    where: { userId },
    select: { category: true },
  });
  const userCategories = interests.map((row) => row.category);

  if (userCategories.length === 0) {
    sendSuccess(res, [], { cursor: null, hasMore: false });
    return;
  }

  let createdAfter: Date | undefined;
  if (dateRange !== 'all') {
    const days = dateRange === '7d' ? 7 : dateRange === '30d' ? 30 : 90;
    createdAfter = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  }

  const where: Record<string, unknown> = {
    project: {
      userId,
      isAutoGenerated: true,
      ...(category ? { category } : { category: { in: userCategories } }),
    },
    ...(type ? { type } : {}),
    ...(minSeverity !== undefined ? { severity: { gte: minSeverity } } : {}),
    ...(tag ? { tags: { has: tag } } : {}),
    ...(createdAfter ? { createdAt: { gte: createdAfter } } : {}),
    ...(search
      ? {
          OR: [
            { title: { contains: search, mode: 'insensitive' } },
            { description: { contains: search, mode: 'insensitive' } },
            { tags: { has: search.toLowerCase() } },
          ],
        }
      : {}),
  };

  if (sort !== 'relevance' && cursor) {
    where['id'] = { lt: cursor };
  }

  const fetchLimit = sort === 'relevance' ? 200 : limit + 1;

  const orderBy =
    sort === 'severity'
      ? { severity: 'desc' as const }
      : sort === 'confidence'
        ? { confidence: 'desc' as const }
        : { createdAt: 'desc' as const };

  let rawInsights = (await prisma.insight.findMany({
    where,
    orderBy,
    take: fetchLimit,
    include: {
      project: { select: { name: true, category: true } },
      savedBy: { where: { userId }, select: { id: true } },
    },
  })) as InsightRow[];

  if (sort === 'relevance') {
    const now = Date.now();
    const thirtyDaysMs = 30 * 24 * 60 * 60 * 1000;
    type ScoredRow = InsightRow & { _score: number };
    rawInsights = (
      rawInsights.map((insight) => {
        const ageMs = now - new Date(insight.createdAt).getTime();
        const recencyScore = Math.max(0, 1 - ageMs / thirtyDaysMs);
        const _score = (insight.severity / 4) * 0.4 + insight.confidence * 0.3 + recencyScore * 0.3;
        return { ...insight, _score } as ScoredRow;
      }) as ScoredRow[]
    )
      .sort((a, b) => b._score - a._score)
      .slice(0, limit + 1);
  }

  const hasMore = rawInsights.length > limit;
  const page = hasMore ? rawInsights.slice(0, limit) : rawInsights;
  const result = page.map(toResult);

  const meta = {
    cursor: page.length > 0 ? page[page.length - 1]!.id : null,
    hasMore,
  };

  if (sort !== 'relevance') {
    await redis.setex(cacheKey, DISCOVER_CACHE_TTL, JSON.stringify({ data: result, meta }));
  }

  sendSuccess(res, result, meta);
});
