import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { sendSuccess } from '../lib/response.js';
import { ValidationError } from '../lib/errors.js';
import { CATEGORY_SOURCES } from '../data/category-sources.js';
import { enqueueScrapeJob } from '../services/queue/jobs.js';

export const interestsRouter = Router();

// Get current user interests
interestsRouter.get('/', async (req, res) => {
  const interests = await prisma.userInterest.findMany({
    where: { userId: req.userId! },
    orderBy: { createdAt: 'asc' },
  });

  sendSuccess(res, interests);
});

const updateSchema = z.object({
  add: z.array(z.string()).default([]),
  remove: z.array(z.string()).default([]),
});

// Update interests (add/remove categories)
interestsRouter.patch('/', async (req, res) => {
  const result = updateSchema.safeParse(req.body);
  if (!result.success) throw new ValidationError(result.error.message);

  const userId = req.userId!;
  const { add, remove } = result.data;

  // Remove interests and their auto-generated projects
  if (remove.length > 0) {
    await prisma.userInterest.deleteMany({
      where: { userId, category: { in: remove as never[] } },
    });

    // Delete auto-generated projects for removed categories
    await prisma.project.deleteMany({
      where: { userId, isAutoGenerated: true, category: { in: remove as never[] } },
    });
  }

  // Add new interests and create projects/sources
  if (add.length > 0) {
    await prisma.userInterest.createMany({
      data: add.map((category) => ({ userId, category: category as never })),
      skipDuplicates: true,
    });

    for (const category of add) {
      // Check if project already exists for this category
      const existing = await prisma.project.findFirst({
        where: { userId, isAutoGenerated: true, category: category as never },
      });
      if (existing) continue;

      const project = await prisma.project.create({
        data: {
          userId,
          name: `${category} Discovery`,
          description: `Auto-generated discovery project for ${category}`,
          isAutoGenerated: true,
          category: category as never,
          keywords: [category],
        },
      });

      const sources = CATEGORY_SOURCES[category];
      if (!sources) continue;

      for (const sourceData of sources) {
        const source = await prisma.source.create({
          data: {
            projectId: project.id,
            platform: sourceData.platform,
            url: sourceData.url,
          },
        });

        await prisma.scrapeJob.create({
          data: { sourceId: source.id, status: 'PENDING' },
        });

        await enqueueScrapeJob(source.id);
      }
    }
  }

  const interests = await prisma.userInterest.findMany({
    where: { userId },
    orderBy: { createdAt: 'asc' },
  });

  sendSuccess(res, interests);
});
