import { useState, useCallback } from 'react';
import { useSaved } from '../hooks/useSaved';
import { useSpecs } from '../hooks/useSpecs';
import { useSpecGeneration } from '../hooks/useAnalysis';
import { useInterests } from '../hooks/useInterests';
import { useSpecPolling } from '../hooks/useJobStatus';
import { useToast } from '../hooks/useToast';
import { DiscoverInsightCard } from '../components/discover/DiscoverInsightCard';
import { Loading } from '../components/ui/Loading';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { CATEGORIES } from '@promptops/shared';
import { api } from '../lib/api.js';
import type { Project } from '@promptops/shared';

export function SavedInsights() {
  const { savedInsights, loading, unsaveInsight } = useSaved();
  const { specs, loading: specsLoading, refetch: refetchSpecs } = useSpecs();
  const { generateSpec, loading: generating } = useSpecGeneration();
  const { interests } = useInterests();
  const { addToast } = useToast();
  const [selectedCategory, setSelectedCategory] = useState('');
  const [format, setFormat] = useState('MARKDOWN');
  const [pendingSpecId, setPendingSpecId] = useState<string | null>(null);
  const [expandedSpecId, setExpandedSpecId] = useState<string | null>(null);

  const handleSpecComplete = useCallback(() => {
    addToast({ type: 'success', message: 'Spec generation complete!' });
    setPendingSpecId(null);
    refetchSpecs();
  }, [addToast, refetchSpecs]);

  const { polling: specPolling } = useSpecPolling(pendingSpecId, {
    onComplete: handleSpecComplete,
  });

  const handleUnsave = async (id: string) => {
    try {
      await unsaveInsight(id);
      addToast({ type: 'info', message: 'Insight removed from saved' });
    } catch {
      addToast({ type: 'error', message: 'Failed to remove insight' });
    }
  };

  const handleGenerate = async () => {
    if (!selectedCategory) return;
    try {
      const projectsRes = await api.get<Project[]>('/projects');
      const project = (projectsRes.data ?? []).find(
        (p) => p.category === selectedCategory && p.isAutoGenerated,
      );
      if (!project) {
        addToast({ type: 'error', message: 'No project found for this category' });
        return;
      }
      const result = await generateSpec(project.id, format);
      const specId = (result as { id?: string } | null)?.id;
      if (specId) setPendingSpecId(specId);
      addToast({ type: 'info', message: 'Spec generation started...' });
    } catch (err) {
      addToast({ type: 'error', message: err instanceof Error ? err.message : 'Failed to generate spec' });
    }
  };

  const handleCopy = async (content: string) => {
    await navigator.clipboard.writeText(content);
    addToast({ type: 'success', message: 'Copied to clipboard' });
  };

  const handleExportMarkdown = (content: string, title: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/[^a-zA-Z0-9-_]/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const userCategories = CATEGORIES.filter((c) =>
    interests.some((i) => i.category === c.value),
  );

  if (loading) return <Loading message="Loading saved insights..." />;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Saved Insights</h1>

      <Card title="Generate Spec from Insights">
        <div className="flex flex-wrap gap-2">
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="rounded-lg border border-gray-300 px-3 py-2 text-sm"
          >
            <option value="">Select category...</option>
            {userCategories.map((c) => (
              <option key={c.value} value={c.value}>{c.label}</option>
            ))}
          </select>
          <select
            value={format}
            onChange={(e) => setFormat(e.target.value)}
            className="rounded-lg border border-gray-300 px-3 py-2 text-sm"
          >
            <option value="MARKDOWN">Markdown</option>
            <option value="CLAUDE_CODE">Claude Code</option>
            <option value="LINEAR">Linear</option>
          </select>
          <Button onClick={handleGenerate} disabled={generating || specPolling || !selectedCategory}>
            {generating ? 'Queueing...' : specPolling ? 'Generating...' : 'Generate Spec'}
          </Button>
        </div>
      </Card>

      {savedInsights.length === 0 ? (
        <div className="py-12 text-center">
          <p className="text-gray-500">No saved insights yet.</p>
          <p className="mt-1 text-sm text-gray-400">
            Save interesting insights from the Discover page to build your spec.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {savedInsights.map((insight) => (
            <DiscoverInsightCard
              key={insight.id}
              insight={insight}
              onSave={() => {}}
              onUnsave={handleUnsave}
            />
          ))}
        </div>
      )}

      {/* Generated Specs */}
      {!specsLoading && specs.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-xl font-bold text-gray-900">Generated Specs</h2>
          {specs.map((spec) => {
            const isGenerating = spec.content === 'Generating...';
            return (
              <Card key={spec.id}>
                <div className="flex items-center justify-between">
                  <h3 className="font-medium text-gray-900">{spec.title}</h3>
                  <div className="flex items-center gap-2">
                    <Badge variant="info">{spec.format}</Badge>
                    {isGenerating ? (
                      <Badge variant="warning">Generating...</Badge>
                    ) : (
                      <Button
                        variant="ghost"
                        onClick={() => setExpandedSpecId(expandedSpecId === spec.id ? null : spec.id)}
                      >
                        {expandedSpecId === spec.id ? 'Collapse' : 'Expand'}
                      </Button>
                    )}
                  </div>
                </div>
                {!isGenerating && expandedSpecId === spec.id ? (
                  <div className="mt-4 space-y-3">
                    <pre className="whitespace-pre-wrap rounded-lg bg-gray-50 p-4 text-sm">{spec.content}</pre>
                    <div className="flex gap-2">
                      <Button variant="secondary" onClick={() => handleCopy(spec.content)}>
                        Copy to Clipboard
                      </Button>
                      <Button variant="ghost" onClick={() => handleExportMarkdown(spec.content, spec.title)}>
                        Export Markdown
                      </Button>
                    </div>
                  </div>
                ) : !isGenerating ? (
                  <p className="mt-2 line-clamp-3 text-sm text-gray-500">{spec.content}</p>
                ) : null}
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
