import { useState, useCallback } from 'react';
import { useSaved } from '../hooks/useSaved';
import { useSpecGeneration } from '../hooks/useAnalysis';
import { useInterests } from '../hooks/useInterests';
import { useSpecPolling } from '../hooks/useJobStatus';
import { useToast } from '../hooks/useToast';
import { DiscoverInsightCard } from '../components/discover/DiscoverInsightCard';
import { Loading } from '../components/ui/Loading';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { CATEGORIES } from '@promptops/shared';
import { api } from '../lib/api.js';
import type { Project } from '@promptops/shared';

export function SavedInsights() {
  const { savedInsights, loading, unsaveInsight, refetch } = useSaved();
  const { generateSpec, loading: generating } = useSpecGeneration();
  const { interests } = useInterests();
  const { addToast } = useToast();
  const [selectedCategory, setSelectedCategory] = useState('');
  const [format, setFormat] = useState('MARKDOWN');
  const [pendingSpecId, setPendingSpecId] = useState<string | null>(null);

  const handleSpecComplete = useCallback(() => {
    addToast({ type: 'success', message: 'Spec generation complete!' });
    setPendingSpecId(null);
  }, [addToast]);

  const { polling: specPolling } = useSpecPolling(pendingSpecId, {
    onComplete: handleSpecComplete,
  });

  const handleUnsave = async (id: string) => {
    try {
      await unsaveInsight(id);
      addToast({ type: 'info', message: 'Insight removed from saved' });
    } catch {
      addToast({ type: 'error', message: 'Failed to remove insight' });
    }
  };

  const handleGenerate = async () => {
    if (!selectedCategory) return;
    try {
      // Find the auto-generated project for this category
      const projectsRes = await api.get<Project[]>('/projects');
      const project = (projectsRes.data ?? []).find(
        (p) => p.category === selectedCategory && p.isAutoGenerated,
      );
      if (!project) {
        addToast({ type: 'error', message: 'No project found for this category' });
        return;
      }
      const result = await generateSpec(project.id, format);
      const specId = (result as { id?: string } | null)?.id;
      if (specId) setPendingSpecId(specId);
      addToast({ type: 'info', message: 'Spec generation started...' });
    } catch (err) {
      addToast({ type: 'error', message: err instanceof Error ? err.message : 'Failed to generate spec' });
    }
  };

  const userCategories = CATEGORIES.filter((c) =>
    interests.some((i) => i.category === c.value),
  );

  if (loading) return <Loading message="Loading saved insights..." />;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Saved Insights</h1>

      <Card title="Generate Spec from Insights">
        <div className="flex flex-wrap gap-2">
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="rounded-lg border border-gray-300 px-3 py-2 text-sm"
          >
            <option value="">Select category...</option>
            {userCategories.map((c) => (
              <option key={c.value} value={c.value}>{c.label}</option>
            ))}
          </select>
          <select
            value={format}
            onChange={(e) => setFormat(e.target.value)}
            className="rounded-lg border border-gray-300 px-3 py-2 text-sm"
          >
            <option value="MARKDOWN">Markdown</option>
            <option value="CLAUDE_CODE">Claude Code</option>
            <option value="LINEAR">Linear</option>
          </select>
          <Button onClick={handleGenerate} disabled={generating || specPolling || !selectedCategory}>
            {generating ? 'Queueing...' : specPolling ? 'Generating...' : 'Generate Spec'}
          </Button>
        </div>
      </Card>

      {savedInsights.length === 0 ? (
        <div className="py-12 text-center">
          <p className="text-gray-500">No saved insights yet.</p>
          <p className="mt-1 text-sm text-gray-400">
            Save interesting insights from the Discover page to build your spec.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {savedInsights.map((insight) => (
            <DiscoverInsightCard
              key={insight.id}
              insight={insight}
              onSave={() => {}}
              onUnsave={handleUnsave}
            />
          ))}
        </div>
      )}
    </div>
  );
}
